import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import "../../assets/scss/style.scss";
import { NextUIProvider } from "@nextui-org/system";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { AuthProviders } from "@/Components/AuthProviders";

import { ReduxProvider } from "@/store/provider";
import { Toaster, toast } from "sonner";

const rubikFont = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "MultiPlast",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${rubikFont.className} `}>
        <ReduxProvider>
          <AuthProviders>
            <NextIntlClientProvider messages={messages}>
              <NextUIProvider className=" w-full h-full">
                {children}
                <Toaster
                  position="top-right"
                  closeButton
                  richColors
                  duration={5000}
                />
              </NextUIProvider>
            </NextIntlClientProvider>
          </AuthProviders>
        </ReduxProvider>
      </body>
    </html>
  );
}
